@ATMSimulador_HostAddress = http://localhost:5059

  # Solicitud de Registro
  POST {{ATMSimulador_HostAddress}}/UsuariosService.svc
  Content-Type: text/xml
  SOAPAction: "http://atm.com/service/Registro"

  <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
    <soap:Header/>
    <soap:Body>
      <ser:Registro>
        <ser:usuarioDto>
          <ser:NombreUsuario>javier</ser:NombreUsuario>
          <ser:Pin>5678</ser:Pin>
        </ser:usuarioDto>
      </ser:Registro>
    </soap:Body>
  </soap:Envelope>
  ###

# Solicitud de Login
POST {{ATMSimulador_HostAddress}}/UsuariosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/Login"

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:Login>
      <ser:usuarioDto>
        <ser:NombreUsuario>selvin</ser:NombreUsuario>
        <ser:Pin>1234</ser:Pin>
      </ser:usuarioDto>
    </ser:Login>
  </soap:Body>
</soap:Envelope>

###

# Solicitud para Obtener Datos del Usuario
POST {{ATMSimulador_HostAddress}}/UsuariosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/GetUserData"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwianRpIjoiZjkwOWM3ZGYtN2EwOS00MTFlLTgwNzMtZjFjYzVjM2YzMTY3Iiwic3ViIjoic2VsdmluIiwibmJmIjoxNzE3OTAxNjg3LCJleHAiOjE3MTg1MDY0ODcsImlhdCI6MTcxNzkwMTY4NywiaXNzIjoiaHR0cHM6Ly9pZC5zZWx2aW5tZWRpbmEuY29tIiwiYXVkIjoiaHR0cHM6Ly9zZWx2aW5tZWRpbmEuY29tIn0.CKK6QF4hgVwYfGl3K9we8FZxEmZVRC-cGvsmEAFeyNg

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ser:GetUserData xmlns:ser="http://atm.com/service/"/>
  </soap:Body>
</soap:Envelope>
###

# Solicitud para Obtener Datos del Usuario
POST {{ATMSimulador_HostAddress}}/UsuariosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/GetUserData"
Authorization: Bearer eyfeg35

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ser:GetUserData xmlns:ser="http://atm.com/service/">
      <ser:token>eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwianRpIjoiZjkwOWM3ZGYtN2EwOS00MTFlLTgwNzMtZjFjYzVjM2YzMTY3Iiwic3ViIjoic2VsdmluIiwibmJmIjoxNzE3OTAxNjg3LCJleHAiOjE3MTg1MDY0ODcsImlhdCI6MTcxNzkwMTY4NywiaXNzIjoiaHR0cHM6Ly9pZC5zZWx2aW5tZWRpbmEuY29tIiwiYXVkIjoiaHR0cHM6Ly9zZWx2aW5tZWRpbmEuY29tIn0.CKK6QF4hgVwYfGl3K9we8FZxEmZVRC-cGvsmEAFeyNg</ser:token>
    </ser:GetUserData>
  </soap:Body>
</soap:Envelope>
###

# Crear Servicio
POST {{ATMSimulador_HostAddress}}/ServiciosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/CrearServicio"

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:CrearServicio>
      <ser:servicioDto>
        <ser:NombreServicio>Hondutel</ser:NombreServicio>
        <ser:Descripcion>Pago de servicio publico Hondutel.</ser:Descripcion>
      </ser:servicioDto>
    </ser:CrearServicio>
  </soap:Body>
</soap:Envelope>

###

# Editar Servicio
POST {{ATMSimulador_HostAddress}}/ServiciosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/EditarServicio"

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:EditarServicio>
      <ser:servicioDto>
        <ser:ServicioId>2</ser:ServicioId>
        <ser:NombreServicio>SANAA</ser:NombreServicio>
        <ser:Descripcion>Pago de servicio público SANAA</ser:Descripcion>
      </ser:servicioDto>
    </ser:EditarServicio>
  </soap:Body>
</soap:Envelope>

###

# Listar Todos los Servicios
POST {{ATMSimulador_HostAddress}}/ServiciosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/ListarServicios"

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ser:ListarServicios xmlns:ser="http://atm.com/service/"/>
  </soap:Body>
</soap:Envelope>

###

# Listar Servicio por ID
POST {{ATMSimulador_HostAddress}}/ServiciosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/ListarServicioPorId"

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:ListarServicioPorId>
      <ser:servicioId>1</ser:servicioId>
    </ser:ListarServicioPorId>
  </soap:Body>
</soap:Envelope>

###
