@ATMSimulador_HostAddress = http://localhost:5059

#
POST {{ATMSimulador_HostAddress}}/api/Usuarios1/login
Content-Type: application/xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:GetLoginRequest>
      <ser:NombreUsuario>selvin</ser:NombreUsuario>
      <ser:Pin>1234</ser:Pin>
    </ser:GetLoginRequest>
  </soap:Body>
</soap:Envelope>
###
# Va a obtener el wsdl
GET {{ATMSimulador_HostAddress}}/api/Usuarios1?wsdl

###