@ATMSimulador_HostAddress = http://localhost:5059

#
POST {{ATMSimulador_HostAddress}}/api/Usuarios2/login
Content-Type: application/xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:ser="http:atm.com/service/">
  <soap:Header/>
  <soap:Body>
   
  </soap:Body>
</soap:Envelope>
###
