@ATMSimulador_HostAddress = http://localhost:5059


# Aperturar Cuenta
POST {{ATMSimulador_HostAddress}}/CuentasService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/AperturarCuenta"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3IiwianRpIjoiNDA4NTUyMzEtNDRkZS00YTBlLWFmNzAtZGJhZDk0NGQ3OGRlIiwic3ViIjoieW9uaSIsIm5iZiI6MTcxODAwMjEzNiwiZXhwIjoxNzE4NjA2OTM2LCJpYXQiOjE3MTgwMDIxMzYsImlzcyI6Imh0dHBzOi8vaWQuc2VsdmlubWVkaW5hLmNvbSIsImF1ZCI6Imh0dHBzOi8vc2VsdmlubWVkaW5hLmNvbSJ9.nuRNDTyInlZIszJTpJaeZ5ITAh-_Y9k4O-g89EI21jU


<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:AperturarCuenta>
      <ser:cuentaDto>
        <ser:NumeroCuenta>cm5QHbqoycZICYAPF9FR+w==</ser:NumeroCuenta>
        <ser:Saldo>Q0Gk1OflDdk=</ser:Saldo>
        <ser:Activa>blABf9FyDas=</ser:Activa>
      </ser:cuentaDto>
    </ser:AperturarCuenta>
  </soap:Body>
</soap:Envelope>

###

# Listar Cuentas
POST {{ATMSimulador_HostAddress}}/CuentasService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/ListarCuentas"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3IiwianRpIjoiNDA4NTUyMzEtNDRkZS00YTBlLWFmNzAtZGJhZDk0NGQ3OGRlIiwic3ViIjoieW9uaSIsIm5iZiI6MTcxODAwMjEzNiwiZXhwIjoxNzE4NjA2OTM2LCJpYXQiOjE3MTgwMDIxMzYsImlzcyI6Imh0dHBzOi8vaWQuc2VsdmlubWVkaW5hLmNvbSIsImF1ZCI6Imh0dHBzOi8vc2VsdmlubWVkaW5hLmNvbSJ9.nuRNDTyInlZIszJTpJaeZ5ITAh-_Y9k4O-g89EI21jU

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:ListarCuentas>
    </ser:ListarCuentas>
  </soap:Body>
</soap:Envelope>

###

# Consultar Saldo
POST {{ATMSimulador_HostAddress}}/CuentasService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/ConsultarSaldo"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3IiwianRpIjoiNDA4NTUyMzEtNDRkZS00YTBlLWFmNzAtZGJhZDk0NGQ3OGRlIiwic3ViIjoieW9uaSIsIm5iZiI6MTcxODAwMjEzNiwiZXhwIjoxNzE4NjA2OTM2LCJpYXQiOjE3MTgwMDIxMzYsImlzcyI6Imh0dHBzOi8vaWQuc2VsdmlubWVkaW5hLmNvbSIsImF1ZCI6Imh0dHBzOi8vc2VsdmlubWVkaW5hLmNvbSJ9.nuRNDTyInlZIszJTpJaeZ5ITAh-_Y9k4O-g89EI21jU

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:ConsultarSaldo>
      <ser:cuentaId>3wv1JXnnXkI=</ser:cuentaId>
    </ser:ConsultarSaldo>
  </soap:Body>
</soap:Envelope>

###
