@ATMSimulador_HostAddress = http://localhost:5059

# Crear Servicio
POST {{ATMSimulador_HostAddress}}/ServiciosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/CrearServicio"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwianRpIjoiZmM3ZGM5YTgtZWQ1OC00YjJkLTkxZWYtYTliYTk1YTI5MzEzIiwic3ViIjoic2VsdmluIiwibmJmIjoxNzE3OTg5OTM5LCJleHAiOjE3MTg1OTQ3MzksImlhdCI6MTcxNzk4OTkzOSwiaXNzIjoiaHR0cHM6Ly9pZC5zZWx2aW5tZWRpbmEuY29tIiwiYXVkIjoiaHR0cHM6Ly9zZWx2aW5tZWRpbmEuY29tIn0.aAfjZbELfPeywqOzE0v9hP9GWAsvWeehaGCrypW55es

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:CrearServicio>
      <ser:servicioDto>
        <ser:NombreServicio>KI/qzS7XWk3HAPq1vc7jzxGPfMqk57sm</ser:NombreServicio>
        <ser:Descripcion>lWkP5cW06wGGKTYMu1waN94XsBqwXq5RfFKUFiras2SI9TCP0FSfNEaBlFqMFQML</ser:Descripcion>
      </ser:servicioDto>
    </ser:CrearServicio>
  </soap:Body>
</soap:Envelope>

###

# Editar Servicio
POST {{ATMSimulador_HostAddress}}/ServiciosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/EditarServicio"

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:EditarServicio>
      <ser:servicioDto>
        <ser:UsuarioId>3</ser:UsuarioId>
        <ser:ServicioId>4</ser:ServicioId>
        <ser:NombreServicio>EEH</ser:NombreServicio>
        <ser:Descripcion>Pago de servicio público EEH ED</ser:Descripcion>
      </ser:servicioDto>
    </ser:EditarServicio>
  </soap:Body>
</soap:Envelope>

###

# Listar Todos los Servicios
POST {{ATMSimulador_HostAddress}}/ServiciosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/ListarServicios"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwianRpIjoiZmM3ZGM5YTgtZWQ1OC00YjJkLTkxZWYtYTliYTk1YTI5MzEzIiwic3ViIjoic2VsdmluIiwibmJmIjoxNzE3OTg5OTM5LCJleHAiOjE3MTg1OTQ3MzksImlhdCI6MTcxNzk4OTkzOSwiaXNzIjoiaHR0cHM6Ly9pZC5zZWx2aW5tZWRpbmEuY29tIiwiYXVkIjoiaHR0cHM6Ly9zZWx2aW5tZWRpbmEuY29tIn0.aAfjZbELfPeywqOzE0v9hP9GWAsvWeehaGCrypW55es

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ser:ListarServicios xmlns:ser="http://atm.com/service/"/>
  </soap:Body>
</soap:Envelope>

###

# Listar Servicio por ID
POST {{ATMSimulador_HostAddress}}/ServiciosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/ListarServicioPorId"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwianRpIjoiZmM3ZGM5YTgtZWQ1OC00YjJkLTkxZWYtYTliYTk1YTI5MzEzIiwic3ViIjoic2VsdmluIiwibmJmIjoxNzE3OTg5OTM5LCJleHAiOjE3MTg1OTQ3MzksImlhdCI6MTcxNzk4OTkzOSwiaXNzIjoiaHR0cHM6Ly9pZC5zZWx2aW5tZWRpbmEuY29tIiwiYXVkIjoiaHR0cHM6Ly9zZWx2aW5tZWRpbmEuY29tIn0.aAfjZbELfPeywqOzE0v9hP9GWAsvWeehaGCrypW55es

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:ListarServicioPorId>
      <ser:servicioId>7o6nvrQKrX4=</ser:servicioId>
    </ser:ListarServicioPorId>
  </soap:Body>
</soap:Envelope>

###
