@ATMSimulador_HostAddress = http://localhost:5059

# Transferir
POST {{ATMSimulador_HostAddress}}/CuentasService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/Transferir"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwianRpIjoiM2JhMGM0MWUtYjYwOC00ZTZjLTlkZTQtYzk3Y2RjMjJmMGI2Iiwic3ViIjoic2VsdmluIiwibmJmIjoxNzE4MDg0MTM5LCJleHAiOjE3MTg2ODg5MzksImlhdCI6MTcxODA4NDEzOSwiaXNzIjoiaHR0cHM6Ly9pZC5zZWx2aW5tZWRpbmEuY29tIiwiYXVkIjoiaHR0cHM6Ly9zZWx2aW5tZWRpbmEuY29tIn0.clcU9_KowSr_m3sgm5QZvhI_T2HZVzaFwZMt0sE5Z_Q
X-HMAC-Signature: 6f7ee072a318660d503cc9eb184de8e9

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/"> <soap:Header/> <soap:Body> <ser:Transferir> <ser:cuentaOrigenId>XwxDg+dcdXQ=</ser:cuentaOrigenId> <ser:cuentaDestinoId>36xwK1wtAuw=</ser:cuentaDestinoId> <ser:monto>7DZyQ9sfBUQ=</ser:monto> </ser:Transferir> </soap:Body> </soap:Envelope>

###
@ATMSimulador_HostAddress = http://localhost:5059

# Realizar Pago
POST {{ATMSimulador_HostAddress}}/PagosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/RealizarPago"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwianRpIjoiM2JhMGM0MWUtYjYwOC00ZTZjLTlkZTQtYzk3Y2RjMjJmMGI2Iiwic3ViIjoic2VsdmluIiwibmJmIjoxNzE4MDg0MTM5LCJleHAiOjE3MTg2ODg5MzksImlhdCI6MTcxODA4NDEzOSwiaXNzIjoiaHR0cHM6Ly9pZC5zZWx2aW5tZWRpbmEuY29tIiwiYXVkIjoiaHR0cHM6Ly9zZWx2aW5tZWRpbmEuY29tIn0.clcU9_KowSr_m3sgm5QZvhI_T2HZVzaFwZMt0sE5Z_Q
X-HMAC-Signature: 3f4624d2b0a6dfc7de6d678219565a95

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/"> <soap:Header/> <soap:Body> <ser:RealizarPago> <ser:pagoDto> <ser:ServicioId>7o6nvrQKrX4=</ser:ServicioId> <ser:CuentaId>XwxDg+dcdXQ=</ser:CuentaId> <ser:Monto>uMWDTRKEBOc=</ser:Monto> </ser:pagoDto> </ser:RealizarPago> </soap:Body> </soap:Envelope>

###
