@ATMSimulador_HostAddress = http://localhost:5059

# Transferir
POST {{ATMSimulador_HostAddress}}/CuentasService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/Transferir"

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:Transferir>
      <ser:cuentaOrigenId>3</ser:cuentaOrigenId>
      <ser:cuentaDestinoId>5</ser:cuentaDestinoId>
      <ser:monto>100.00</ser:monto>
    </ser:Transferir>
  </soap:Body>
</soap:Envelope>

###
@ATMSimulador_HostAddress = http://localhost:5059

# Realizar Pago
POST {{ATMSimulador_HostAddress}}/PagosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/RealizarPago"

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:RealizarPago>
      <ser:pagoDto>
        <ser:ServicioId>1</ser:ServicioId>
        <ser:CuentaId>3</ser:CuentaId>
        <ser:Monto>150.00</ser:Monto>
        <ser:FechaPago>2024-06-09T00:00:00</ser:FechaPago>
      </ser:pagoDto>
    </ser:RealizarPago>
  </soap:Body>
</soap:Envelope>
###
