@ATMSimulador_HostAddress = http://localhost:5059

# Solicitud de Registro
POST {{ATMSimulador_HostAddress}}/UsuariosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/Registro"

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/">
  <soap:Header/>
  <soap:Body>
    <ser:Registro>
      <ser:usuarioDto>
        <ser:NombreUsuario>Ub/eVS2NqBM=</ser:NombreUsuario>
        <ser:Pin>B81wXZLL3Mk=</ser:Pin>
      </ser:usuarioDto>
    </ser:Registro>
  </soap:Body>
</soap:Envelope>
###

# Solicitud de Login
POST {{ATMSimulador_HostAddress}}/UsuariosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/Login"
X-HMAC-Signature: 272eed8f85c2acbf0746735aad61b553

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/"> <soap:Header/> <soap:Body> <ser:Login> <ser:usuarioDto> <ser:NombreUsuario>pMIaIZeNA4w=</ser:NombreUsuario> <ser:Pin>B81wXZLL3Mk=</ser:Pin> </ser:usuarioDto> </ser:Login> </soap:Body> </soap:Envelope>
###

# Solicitud para Obtener Datos del Usuario
POST {{ATMSimulador_HostAddress}}/UsuariosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/GetUserData"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwianRpIjoiZmM3ZGM5YTgtZWQ1OC00YjJkLTkxZWYtYTliYTk1YTI5MzEzIiwic3ViIjoic2VsdmluIiwibmJmIjoxNzE3OTg5OTM5LCJleHAiOjE3MTg1OTQ3MzksImlhdCI6MTcxNzk4OTkzOSwiaXNzIjoiaHR0cHM6Ly9pZC5zZWx2aW5tZWRpbmEuY29tIiwiYXVkIjoiaHR0cHM6Ly9zZWx2aW5tZWRpbmEuY29tIn0.aAfjZbELfPeywqOzE0v9hP9GWAsvWeehaGCrypW55es

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ser:GetUserData xmlns:ser="http://atm.com/service/">
    </ser:GetUserData>
  </soap:Body>
</soap:Envelope>

###
#Cambio de pin
POST {{ATMSimulador_HostAddress}}/UsuariosService.svc
Content-Type: text/xml
SOAPAction: "http://atm.com/service/CambiarPin"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwianRpIjoiM2JhMGM0MWUtYjYwOC00ZTZjLTlkZTQtYzk3Y2RjMjJmMGI2Iiwic3ViIjoic2VsdmluIiwibmJmIjoxNzE4MDg0MTM5LCJleHAiOjE3MTg2ODg5MzksImlhdCI6MTcxODA4NDEzOSwiaXNzIjoiaHR0cHM6Ly9pZC5zZWx2aW5tZWRpbmEuY29tIiwiYXVkIjoiaHR0cHM6Ly9zZWx2aW5tZWRpbmEuY29tIn0.clcU9_KowSr_m3sgm5QZvhI_T2HZVzaFwZMt0sE5Z_Q
X-HMAC-Signature: 1cc2c65864bf3e3587ffe4980dd9cdca

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://atm.com/service/"> <soap:Header/> <soap:Body> <ser:CambiarPin> <ser:nuevoPin>wDLLLzp4MGk=</ser:nuevoPin> </ser:CambiarPin> </soap:Body> </soap:Envelope>
###
